### ISSUE TITLE
Ability to push changes on periodic commit

### ISSUE THREAD

**Issue by dmg46664** [aaronbieber/periodic-commit-minor-mode#2]
I've been using this successfully, so many thanks!

However I've been bought a Samsung S4 which runs Linux on Dex and now my Google drive syncing solution is no longer applicable. Moving my org files to bitbucket but this means having to push and pull files in order to sync them. Perhaps there is another solution / feature I haven't thought of, but putting the use case here regardless (for feedback).

If it gets annoying enough I may come back with a pull request :-)

**Comment by dmg46664** [comment]
I guess git hooks fill's this function:
https://stackoverflow.com/questions/7925850/how-to-automatically-push-after-committing-in-git

**Comment by aaronbieber** [comment]
Sounds like git hooks will satisfy your need. Adding the ability to automatically push to a predefined upstream would probably not be difficult, but I would only add it if it was necessary.

Glad this package has been of use to you! I thought I was the only one using it to be honest...
